export default function Footer() {
  const year = new Date().getFullYear();

  return (
    <footer className="mt-auto border-t border-[#23262F] bg-[#09090C]">
      <div className="mx-auto max-w-screen-xl px-4 py-8 sm:px-6 lg:px-8">

        {/* Disclaimer — non-negotiable, always visible */}
        <div className="mb-6 rounded-lg border border-[#23262F] bg-[#13151B] px-4 py-3">
          <p className="text-[11px] font-semibold uppercase tracking-widest text-[#C9A84C]">
            Important Disclaimer
          </p>
          <p className="mt-1 text-[12px] leading-relaxed text-[#555B6B]">
            All content on Project Black Rod is generated by AI and provided for informational
            and educational purposes only. Nothing on this platform constitutes financial,
            investment, or trading advice. Market analysis does not guarantee future results.
            All market data shown in this preview build is simulated. Trade at your own risk.
          </p>
        </div>

        <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex items-center gap-2.5">
            <div className="flex flex-col">
              <span className="text-[13px] font-bold text-[#E4E6EB]">Project Black Rod</span>
              <span className="text-[11px] text-[#555B6B]">
                © {year} · UI Preview Build · APIs not yet integrated
              </span>
            </div>
          </div>
          <nav className="flex gap-4">
            {["Disclaimer", "Privacy", "Terms"].map((link) => (
              <a
                key={link}
                href="#"
                className="text-[12px] text-[#555B6B] transition-colors hover:text-[#C9A84C]"
              >
                {link}
              </a>
            ))}
          </nav>
        </div>

      </div>
    </footer>
  );
}
